#!bin/bash

# Updating system
sudo apt update && apt upgrade -y

# Installing apps with apt
sudo apt install curl wget gpg flatpak nextcloud-desktop -y

# Adding Brave repo and installing it
sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list

sudo apt update && apt install brave-browser -y

# Installing apps with snap
sudo snap refresh

sudo snap install code --classic node --classic intellij-idea-ultimate --classic pycharm-professional --classic

# Check if flathub repo is already added
if flatpak remote-list | grep -q 'flathub'
then
    echo "Flathub is already added."
else
    echo "Adding flathub repository..."
    sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
fi

# Installing apps via flathub
sudo flatpak install flathub com.github.Eloston.UngoogledChromium -y
